Replace mcrypt with sodium
kiddivouchers/kohana-core pull request #3
Opened 2020-09-29 12:06 UTC by deangray82

2020-09-29 16:09 UTC, cs278 requested changes

2020-09-29 16:09 UTC, cs278 commented on classes/kohana/encrypt.php
> +	private static $default = 'default';
Keep this public, no need to change it and break something unintentionally.

2020-09-29 16:09 UTC, cs278 commented on classes/kohana/encrypt.php
> +	private static $instances = [];
Same with this.

2020-09-29 16:09 UTC, cs278 commented on classes/kohana/encrypt.php
> +	public function __construct($key)
Might as well we've bumped PHP requirement to 7.3

```suggestion
	public function __construct(string $key)
```

2020-09-29 16:09 UTC, cs278 commented on classes/kohana/encrypt.php
> +		$this->key = hex2bin($key);
I'd add a length check and throw an exception if the key is not the correct length to prevent and configuration mistakes.

2020-09-29 16:09 UTC, cs278 commented on classes/kohana/encrypt.php
> +	public static function instance($name = null)
Can we put the methods back in the same order so this PR is easier to review please.

2020-09-29 16:09 UTC, cs278 commented on composer.json
> +		"php": "~7.3"
```suggestion
		"php": "^7.3"
```

2020-09-29 16:09 UTC, cs278 commented on classes/kohana/encrypt.php
> -			mt_srand();
Good riddance!

2020-09-29 16:09 UTC, cs278 commented on classes/kohana/encrypt.php
> +		return base64_encode(bin2hex($nonce.$encryptedData));
Not very efficient converting to hex then base64 encoding it, I don't see any reason to add the additional hex conversion step.

2020-10-01 15:25 UTC, cs278 commented on classes/kohana/encrypt.php
> +		if (mb_strlen($key, '8bit') !== SODIUM_CRYPTO_SECRETBOX_KEYBYTES)
Just use normal `strlen()` to keep in common with the rest of the code.

```suggestion
		if (strlen($key) !== SODIUM_CRYPTO_SECRETBOX_KEYBYTES)
```

2020-10-01 15:26 UTC, cs278 commented on classes/kohana/encrypt.php
> +	 * @return self
```suggestion
	 * @return Encrypt
```

2020-10-01 15:26 UTC, cs278 commented on classes/kohana/encrypt.php
> +			$name = self::$default;
```suggestion
			$name = Encrypt::$default;
```

All of these changes to `self` will break Kohana's extension ability.

2020-10-01 15:27 UTC, cs278 commented on classes/kohana/encrypt.php
> +			$config = \Kohana::$config->load('encrypt')->$name;
```suggestion
			$config = Kohana::$config->load('encrypt')->$name;
```

Not needed as the code is not in a namespace.

2020-10-02 09:09 UTC, cs278 approved these changes
LGTM

2020-10-02 09:10 UTC, cs278 commented
@deangray82 have you tested this?

2020-10-02 09:15 UTC, deangray82 commented
> have you tested this?

Yes, I've tested it locally (successfully encoded and decoded a serialised user record) and on platform.

2020-10-02 09:17 UTC, merged